server:
  port: 8032
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
eureka:
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/
spring:
  application:
    name: eureka_client